“SMAN Situraja Sekolah Unggulan SSN dan SKM”
Sumedang, Kompass Indonesia - SMAN Situraja merupakan salah satu sekolah unggulan di wilayah Sumedang Provinsi Jawa Barat, yang telah berstatus Sekolah Standar Nasional (SSN) dan Rintisan Sekolah Kategori Mandiri (RSKM).  Tahun ajaran 2012/2013 sekolah ini persiapan menuju Rintisan Sekolah Bertaraf Internasional (RSBI).

“Untuk itu, kami sudah mulai menyiapkan Sumber Daya Manusia (SDM) yang berkualitas dengan meningkatkan wawasan pengetahuan,” ujar Kepsek SMAN Situraja, Dra. Rukmini Yuliati, M.Pd. kepada KI beberapa hari yang lalu.

Menurut Rukmini, perkembangan ilmu pengetahuan dan teknologi telah membawa perubahan di hampir semua aspek kehidupan manusia, dimana berbagai permasalahan hanya dapat di pecahkan kecuali dengan upaya penguasaan dan peningkatan teknologi. Agar mampu berperan dalam persaingan global. “Kita perlu terus mengembangkan dan meningkatkan kualitas SDM. Oleh karena itu, peningkatan kualitas SDM merupakan kenyataan yang harus dilakukan secara terencana, terarah, insentif, efektif, dan efisien dalam proses pembangunan agar mampu bersaing dalam menjalani era globalisasi tersebut,” tuturnya dengan ramah. 

Lanjutnya, “Upaya yang kami lakukan saat ini termasuk meningkatkan wawasan pengetahuan para guru, siswa, tenaga administrasi, pustakawan dengan melakukan berbagai pelatihan di dalam lingkungan sekolah maupun kerja sama dengan lembaga pendidikan yang bonafide di Bandung,” ucap Rukmini. Dikatakan Rukmini, peningkatan SDM yang dilaksanakan saat ini di SMAN Situraja termasuk meliputi penguasaan bahasa inggris, internet, maupun managemen berbasis komputerisasi. Seperti pelatihan data base, sehingga kedepan diharapkan SDM SMAN Situraja dapat meningkat dengan era globalisasi.

Di paparkan Dra. Rukmini Yuliawati, M.Pd, “Sekolah ini merupakan salah satu sekolah yang banyak melahirkan lulusan yang berkualitas, terbukti dengan banyaknya yang melanjutkan ke jenjang lebih tinggi dan masuk ke perguruan tinggi,” tegasnya. Sedangkan  perkembangan sekolah ini menjadi SSN dan SKM tentu kami melaksanakan dan menerapkan Sistim Kredit Semester (SKS) yakni penerapan program pendidikan yang menempatkan peserta didik sebagai subyek. Sistem ini, pembelajaran berpusat pada peserta didik yaitu bagaimana peserta didik belajar diberikan kebebasan untuk merencanakan kegiatan belajarnya, sesuai dengan minat kemampuan dan harapan masing-masing. Selain itu, berbagai usaha pengembangan pendidikan yang telah berkualiatas tinggi dengan tuntutan kebutuhan masyarakat. “Kita berharap bahwa pendidikan yang me-miliki arah dan sasaran pada level ini menjadikan SDM Sumedang lebih baik di masa yang akan datang. Sehingga mampu bersaing di wilayah sendiri maupun berprestasi pula dalam skala yang lebih besar serta dapat memberikan kontribusi kepada pembangunan bangsa,” urainya. Mawardi